apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy-data
spec:
  selector:
    matchLabels:
      app: postgres-deploy-data
  template:
    metadata:
      labels:
        app: postgres-deploy-data
    spec:
      containers:
      - name: postgres-deploy-data
        image: postgres:17.10
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: kamaluser
        - name: POSTGRES_PASSWORD
          value: admin123
        - name: POSTGRES_DB
          value: kamaldb
          
