apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: axion-deploy-ui
  template:
    metadata:
      labels:
        app: axion-deploy-ui
    spec:
      containers:
      - name: axion-deploy
        image: devopsinsiders/axion-ui
        ports:
        - containerPort: 80
