name: "Dev Terraform Workflow"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 0e25357b-8270-49e7-99b6-eb2161b7f3a0
          tenant-id: d044667f-42ca-49f4-8d4f-684197e03471
          subscription-id: caba13fb-1019-44a6-817f-cc5eb0ec1c55
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 0e25357b-8270-49e7-99b6-eb2161b7f3a0
          tenant-id: d044667f-42ca-49f4-8d4f-684197e03471
          subscription-id: caba13fb-1019-44a6-817f-cc5eb0ec1c55     
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev              
          
