name: "Dev Terraform  Workflow"

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: persistent
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: fdd23cd2-6da2-4640-8804-85d92910da8f
          tenant-id: 1171f52f-e7a8-4e84-bc3c-786a8db0cac7
          subscription-id: 7d7e4c65-1bfb-4455-b143-d0d76737869b
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev    
        
  terraform-apply:    
    runs-on: persistent
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev 
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: fdd23cd2-6da2-4640-8804-85d92910da8f
          tenant-id: 1171f52f-e7a8-4e84-bc3c-786a8db0cac7
          subscription-id: 7d7e4c65-1bfb-4455-b143-d0d76737869b    
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev              
          
